export const Icons = {
  logo: require('../assets/images/logo.png'),
  logoSm: require('../assets/images/logo-sm.png'),
  logoWhite: require('../assets/images/logo-white.png'),
  User1: require('../assets/images/user-1.jpg'),
  Home: require('../assets/images/home.png'),
  Grid: require('../assets/images/grid.png'),
  Message: require('../assets/images/message-circle.png'),
  Cart: require('../assets/images/shopping-cart.png'),
  Person: require('../assets/images/person.png'),
  Search: require('../assets/images/search.png'),
  BookMark: require('../assets/images/bookmark.png'),
  BellOutline: require('../assets/images/bell-outline.png'),
  BookmarkOutline: require('../assets/images/bookmark-outline.png'),
  GridOutline: require('../assets/images/grid-outline.png'),
  HomeOutline: require('../assets/images/home-outline.png'),
  PersonOutline: require('../assets/images/person-outline.png'),
  CartOutline: require('../assets/images/shopping-cart-outline.png'),
  MessageOutline: require('../assets/images/message-circle-outline.png'),
  FilterOutline: require('../assets/images/options-2-outline.png'),
  ArrowBack: require('../assets/images/arrow-back-outline.png'),
  More: require('../assets/images/more-vertical-outline.png'),
  Star: require('../assets/images/star.png'),
  Close: require('../assets/images/close-outline.png'),
  Illus1: require('../assets/images/illus-1.png'),
  Illus2: require('../assets/images/illus-2.png'),
  Apple: require('../assets/images/apple.png'),
  Google: require('../assets/images/google.png'),
  Facebook: require('../assets/images/facebook.png'),
  Calendar: require('../assets/images/calendar.png'),
  EmailOutline: require('../assets/images/email-outline.png'),
  DefaultUser: require('../assets/images/default-user.png'),
  Edit: require('../assets/images/edit.png'),
  ChevronDown: require('../assets/images/chevron-down.png'),
  PlayCircle: require('../assets/images/play-circle.png'),
  FileText: require('../assets/images/file-text.png'),
  Call: require('../assets/images/call.png'),
  MSCard: require('../assets/images/ms-card.png'),

  // Banners

  Banner1: require('../assets/images/banner/40%OFF.png'),
};
